version: "3"
services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: restaurantecommerce
  app:
    image: postgresdb
    ports:
      - 13000:3000